Верстка страницы профиля пользователя Twitter
TchernyavskyDaniil/twitter-demo-frontend pull request #1
Opened 2018-06-15 08:35 UTC by TchernyavskyDaniil

Шрифт - херня, не такой как нужен по макету . 
Некоторые активные элементы не успел реализовать . 
Претиром проверял и правил . 
Картинка профиля пока в свг, поправлю . 

Я понимаю, что все выше может помешать проверке. Но посмотри пожалуйста, я хочу понять косяки по остальным моментам. Еле успел доделать.

2018-06-15 22:14 UTC, evgenyrodionov commented
Во-первых, английский язык
Во-вторых, что такое main-frontend во фронтэнд-приложении? Как это понимать?

2018-06-15 22:18 UTC, TchernyavskyDaniil commented
Могу ли я от новой ветки сделать сейчас, а эту удалить? Ничего страшного, проверишь сейчас?

2018-06-15 22:25 UTC, imevro commented
Нахуя ты это сделал?

2018-06-15 22:25 UTC, imevro commented
блядь

2018-06-15 22:25 UTC, imevro commented
сука

2018-06-15 22:25 UTC, imevro commented
блядь

2018-06-15 22:25 UTC, imevro commented
куда мне блядь 14 комментариев отправлять?

2018-06-15 22:25 UTC, imevro commented
СУКА

2018-06-15 22:26 UTC, imevro commented
КТО ТЕБЕ РАЗРЕШАЛ

2018-06-15 22:26 UTC, TchernyavskyDaniil commented
бля

2018-06-15 22:26 UTC, imevro commented
НАХУЯ ТЫ СПРАШИВАЕШЬ ВОПРОСЫ ЕСЛИ ДЕЛАЕШЬ ВСЁ ПО-СВОЕМУ

2018-06-15 22:27 UTC, imevro commented on public/avatar.svg
> +<image id="image0" width="400" height="400" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAAAXNSR0IArs4c6QAAGAxJREFUeAHt3VnMXlP7B+DV4jNG1FAhSEhUJRygQQQxpMGJkEgFFWMl1
зачем ты пнг засунул в свг?

2018-06-15 22:27 UTC, imevro commented on src/App.jsx
> +import Profile from "./Profile/index";
не нужо добавлять индекс, вебпак и так ищет индекс файл

2018-06-15 22:27 UTC, imevro commented on src/App.jsx
> +class App extends Component {
зачем класс?

2018-06-15 22:27 UTC, imevro commented on src/App.jsx
> +import React, { Component } from "react";
зачем ты используешь расширение джсх? не нужно

2018-06-15 22:27 UTC, imevro commented on src/Profile/Header/Nav/nav.jsx
> +const TwitterSvg = styled.img`
завтра станет новомодным форматом, что станет с твоим неймингом?

2018-06-15 22:27 UTC, imevro commented on src/Profile/Header/Nav/nav.jsx
> +const SearchContainer = styled.div`
упрости, ты не на ангуларе пишешь чтобы плодить контейнеры

2018-06-15 22:27 UTC, imevro commented on src/Profile/Main/InfoPerson/information.jsx
> +  letter-spacing: 0.01px;
нет

2018-06-15 22:27 UTC, imevro commented on src/Profile/Main/Posts/posts.jsx
> +import React, { Component } from "react";
поч компонент называется с маленькой буквы

2018-06-15 22:27 UTC, imevro commented on src/Profile/Main/Posts/posts.jsx
> +    left: -4%;
что это

2018-06-15 22:27 UTC, imevro commented on src/Profile/Main/Posts/posts.jsx
> +  grid-template-columns: ${props => (props.imgWidth ? "1fr" : "126px 1fr")};
и где поддержка этого?

2018-06-15 22:27 UTC, imevro commented on src/Profile/Main/Posts/posts.jsx
> +              <NicknameLink to="/EveryInteract">@EveryInteract</NicknameLink>
засовывай всё в один компонент и пропы, не нужно такую лапшу плодить

2018-06-15 22:27 UTC, imevro commented on src/index.css
> +  list-style: none;
нет конечно

2018-06-15 22:27 UTC, imevro commented on src/Profile/index.jsx
> +import Main from "./Main/main";
зачем у тебя дублируется? клади в index.js и используй как import Main from './Main'

и компоненты называются с большой буквы

2018-06-15 22:27 UTC, imevro commented on src/registerServiceWorker.js
> +/* eslint-disable
кто тебе разрешал это делать?

2018-06-15 22:27 UTC, TchernyavskyDaniil commented
Шо делаем тогда, все, я проебал шанс?

2018-06-15 22:37 UTC, TchernyavskyDaniil commented on src/Profile/Main/Posts/posts.jsx
> +  grid-template-columns: ${props => (props.imgWidth ? "1fr" : "126px 1fr")};
В смысле, гриды же нормально поддерживаются. Ты же об этом?

2018-06-15 23:21 UTC, TchernyavskyDaniil commented on src/Profile/index.jsx
> +import Main from "./Main/main";
Почему в индекс жс (который принимает Апп?). Почему дублируется тут что - то? Я не понял этот момент короче.

2018-06-18 05:51 UTC, evgenyrodionov commented
ты нахуя бранч удалил?

2018-06-18 05:51 UTC, evgenyrodionov commented
как я буду смотреть что ты исправил а что нет

2018-06-18 05:53 UTC, TchernyavskyDaniil commented
Женя, ты же сказал, что я не правильно ветку назвал и ПР на русском. Я решил, что необходимо новую ветку создать с нормальным названием

https://github.com/TchernyavskyDaniil/twitter-demo-frontend/pull/2

2018-06-18 05:55 UTC, evgenyrodionov commented
как я буду смотреть что ты исправил а что нет

2018-06-18 05:55 UTC, TchernyavskyDaniil commented
Там все коммиты и с этой ветки.

2018-06-18 05:56 UTC, evgenyrodionov commented
а мои замечания?

2018-06-18 05:56 UTC, evgenyrodionov commented
как они блядь переместятся?

2018-06-18 05:56 UTC, TchernyavskyDaniil commented
Я все исправил.

2018-06-18 05:57 UTC, evgenyrodionov commented
с хуя ли я тебе должен верить?

2018-06-18 05:57 UTC, evgenyrodionov commented
я верю только интерфейсу гитхаба

2018-06-18 05:57 UTC, evgenyrodionov commented
который мне покажет что ты исправил а что нет

2018-06-18 05:57 UTC, TchernyavskyDaniil commented
Тогда я кикнут получается?

2018-06-18 05:58 UTC, evgenyrodionov commented
иди возвращай всё обратно в этот бранч и открывай этот пуллреквест

2018-06-18 05:58 UTC, TchernyavskyDaniil commented
Как я все верну если ветка удалена и там уже коммиты все?

2018-06-18 05:59 UTC, evgenyrodionov commented
мне похуй

2018-06-18 05:59 UTC, evgenyrodionov commented
это не моя задача

2018-06-18 06:01 UTC, TchernyavskyDaniil commented
Ладно, постараюсь

2018-06-18 06:13 UTC, TchernyavskyDaniil commented
Посмотри пожалуйста сейчас

2018-06-18 06:41 UTC, evgenyrodionov commented
перевесить запрос на ревью не хочешь?

2018-06-18 06:42 UTC, TchernyavskyDaniil commented
хочу, но не мог почему - то раньше, пока не отписал х)

2018-06-18 08:57 UTC, imevro requested changes

2018-06-18 08:57 UTC, evgenyrodionov commented on .eslintrc
> +    "arrow-body-style": ["error", "always"],
кто тебе разрешал трогать правила еслинта?

2018-06-18 08:57 UTC, evgenyrodionov commented on src/App.js
> +import Profile from "./Profile/index";
вебпак при импорте директории ищет индексджс файл

2018-06-18 08:57 UTC, evgenyrodionov commented on src/App.js
> +        <Switch>
зачем тут див?

2018-06-18 08:57 UTC, evgenyrodionov commented on src/Profile/Header/Header.js
> +  width: 83%;
и что это?

2018-06-18 08:57 UTC, evgenyrodionov commented on src/Profile/Header/Header.js
> +import React from "react";
Header/Header.js → Header/index.js

2018-06-18 08:57 UTC, evgenyrodionov commented on src/Profile/Header/Nav/Navigation/Navigation.js
> +  state = {
зачем это здесь?

2018-06-18 08:57 UTC, evgenyrodionov commented on src/Profile/Header/ProfileStats/Stats.js
> +  &.normal {
зачем это?

2018-06-18 08:57 UTC, evgenyrodionov commented on src/Profile/Header/ProfileStats/Stats.js
> +        link: "/likes",
перестань так делать

2018-06-18 08:57 UTC, evgenyrodionov commented on src/Profile/Main/InfoPerson/Information.js
> +import React, { Component } from "react";
убери такую уебанскую вложенность директорий и файлов, пять уровней

2018-06-18 10:28 UTC, TchernyavskyDaniil commented on src/Profile/Header/ProfileStats/Stats.js
> +        link: "/likes",
Что именно?

2018-06-18 22:45 UTC, TchernyavskyDaniil commented
https://twitter-demo-frontend-nslkvglpcx.now.sh/EveryInteract - Demo

2018-06-19 08:36 UTC, TchernyavskyDaniil commented
Евгений, а еще есть время закинуть коммит? Кнопку и инпут поиска вынес как отдельные компоненты в UI.

2018-06-19 11:17 UTC, imevro requested changes

2018-06-19 11:17 UTC, evgenyrodionov commented on src/Profile/Header.js
> +    <ProfileCanopyHeader alt="Profile Image" src="/img/profile.png" />
что такое канопи вообще

2018-06-19 11:20 UTC, TchernyavskyDaniil commented on src/Profile/Header.js
> +    <ProfileCanopyHeader alt="Profile Image" src="/img/profile.png" />
Навес, купол
У меня такие ассоциации это большое полотно в виде фото вызвало

2018-06-20 08:54 UTC, TchernyavskyDaniil commented
https://twitter-demo-frontend-jxofcgzuvy.now.sh/EveryInteract - Demo new

2018-06-20 21:25 UTC, imevro approved these changes

2018-06-22 22:30 UTC, merged

2018-06-22 22:30 UTC, evgenyrodionov commented
Не забудь сделать гит пулл в мастере перед созданием новых бранчей от него