Edit profile page
TchernyavskyDaniil/twitter-demo-frontend pull request #4
Opened 2018-06-27 07:47 UTC by TchernyavskyDaniil

https://github.com/TchernyavskyDaniil/twitter-demo-frontend/pull/3 - Старый ПР. 
Я хз мне ли его надо было закрывать. Так шо не трогаю.
Текущая проверка связанна с 1-3 заданиями 2 этапа

2018-06-29 08:34 UTC, TchernyavskyDaniil commented
Demo https://twitter-demo-frontend-cbhvycaqyx.now.sh/EveryInteract

2018-06-29 22:21 UTC, imevro requested changes

2018-06-29 22:21 UTC, evgenyrodionov commented on src/App.js
> +import OtherUrl from "./OtherUrl";
слабое название

2018-06-29 22:21 UTC, evgenyrodionov commented on src/Profile/Stats/Stat.js
> +        isActive={isMainNavActive}
почему всю эту проверку нельзя запихнуть только в этот проп?

2018-06-29 22:21 UTC, evgenyrodionov commented on src/Profile/Tweets/index.js
> +            {tweet.tweetText.match(/[^\s]+/g).length >= 16 ? (
wtf

2018-06-29 22:21 UTC, evgenyrodionov commented on src/Profile/Tweets/index.js
> +                    )}...`}</InfoText>
блядь ебать это что за проверок вавилонская башня? треш какой-то

2018-06-30 18:57 UTC, TchernyavskyDaniil commented
https://twitter-demo-frontend-ikzuyxazzw.now.sh 
Demo

2018-07-05 13:35 UTC, imevro approved these changes

2018-07-11 17:02 UTC, merged