API
TchernyavskyDaniil/twitter-demo-frontend pull request #5
Opened 2018-07-03 17:45 UTC by TchernyavskyDaniil

2018-07-05 14:49 UTC, imevro commented
Почему на третьей неделе ПУЛЛРЕКВЕСТ ОПЯТЬ В МАСТЕР?

2018-07-05 14:51 UTC, imevro requested changes

2018-07-05 14:51 UTC, evgenyrodionov commented on src/Profile/Feeds.js
> +            feeds: result
можно упростить до `{ feeds }` если аргумент функции назовёшь как `feeds`

2018-07-05 14:51 UTC, evgenyrodionov commented on src/Profile/Feeds.js
> +          render={() => (
почему рендер, а не компонент?

2018-07-05 14:51 UTC, evgenyrodionov commented on src/utils.js
> +export const dateFormat = type =>
функции называются глаголами

2018-07-05 16:42 UTC, TchernyavskyDaniil commented on src/Profile/Feeds.js
> +          render={() => (
Feeds - компонент содержащий Tweets, Tweets with Replies, Media. В рендере у нас мап твитов с определенными условиями из тернарника, дабы передать нужны пропсы

2018-07-06 08:56 UTC, TchernyavskyDaniil commented
https://twitter-demo-frontend-xtizizwexz.now.sh - Demo

2018-07-06 20:27 UTC, imevro requested changes

2018-07-06 20:27 UTC, imevro commented on src/Profile/Feeds.js
> +                  )}
удобно с таким говном работать?

2018-07-06 20:27 UTC, imevro commented on src/Profile/Media.js
> +        count: prevState.count + mediaElem.media_attachments.length
медиахуелем

2018-07-06 20:27 UTC, imevro commented on src/utils.js
> +export const dateFormating = type =>
глаголом

2018-07-07 13:34 UTC, lomeat commented on src/Profile/Media.js
> +        count: prevState.count + mediaElem.media_attachments.length
тк нельзя из media сделать название в 1 элемент, типа как followers -> follower, я писал mediaObject

2018-07-07 14:15 UTC, TchernyavskyDaniil commented
https://twitter-demo-frontend-rhvxeekbma.now.sh/3

2018-07-11 17:00 UTC, TchernyavskyDaniil commented
Спасибо за курс, жаль что времени нет.

2018-07-11 17:00 UTC, merged